<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-ios</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <SupportedOSPlatformVersion>16.0</SupportedOSPlatformVersion>
    <ApplicationId>net.avaloniaui.cupertino.gallery</ApplicationId>
    <RootNamespace>Cupertino.Gallery</RootNamespace>
    <NoWarn>$(NoWarn);CA1711</NoWarn>
    <!-- Allow the installed Xcode version. -->
    <ValidateXcodeVersion>false</ValidateXcodeVersion>
    <!-- Avalonia.DesignerSupport requires interpretation in Debug builds. -->
    <MtouchInterpreter Condition="'$(Configuration)' == 'Debug'">-all</MtouchInterpreter>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.iOS" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.iOS" Version="3.119.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cupertino.Gallery\Cupertino.Gallery.csproj" />
  </ItemGroup>

</Project>
